server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes Angular → index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy vers le backend
    # En local (docker-compose) : backend = nom du conteneur
    # Sur GKE : backend = nom du Service Kubernetes dans le même namespace
    location /api/ {
        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
